language: scala
sudo: required
jdk:
  - oraclejdk8

scala:
  - 2.11.8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  # Split tests into separate commands ("jobs" in Travis parlance) to avoid any single one exceeding the 50minute timeout 😱
  - sbt ++$TRAVIS_SCALA_VERSION bgzf/test
  - sbt ++$TRAVIS_SCALA_VERSION check/test
  - sbt ++$TRAVIS_SCALA_VERSION cli/test
  - sbt ++$TRAVIS_SCALA_VERSION load/test
  - sbt ++$TRAVIS_SCALA_VERSION seqdoop/test
  - sbt coverageReport

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $HOME/.zinc

after_success: sbt ++$TRAVIS_SCALA_VERSION travis-report

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
