language: scala
sudo: required
jdk:
  - oraclejdk8

scala:
  - 2.11.8

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean
  # Split tests into separate commands ("jobs" in Travis parlance) to avoid any single one exceeding the 50minute timeout 😱
  - sbt ++$TRAVIS_SCALA_VERSION 'test-only org.hammerlab.bgzf.*'
  - sbt ++$TRAVIS_SCALA_VERSION 'test-only org.hammerlab.bam.check.eager.*'
  - sbt ++$TRAVIS_SCALA_VERSION 'test-only org.hammerlab.bam.check.seqdoop.*'
  - sbt ++$TRAVIS_SCALA_VERSION 'test-only org.hammerlab.bam.check.full.*'
  - sbt ++$TRAVIS_SCALA_VERSION 'test-only org.hammerlab.bam.check.BlocksTest org.hammerlab.bam.check.MainTest'
  - sbt ++$TRAVIS_SCALA_VERSION 'test-only org.hammerlab.bam.MainTest org.hammerlab.bam.header.* org.hammerlab.bam.index.* org.hammerlab.bam.iterator.* org.hammerlab.bam.rewrite.* org.hammerlab.bam.spark.*'
  - sbt coverageReport

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
  - $HOME/.zinc

after_success: sbt ++$TRAVIS_SCALA_VERSION travis-report

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
